sudo: false
language: node_js
node_js:
  - "stable"

install:
  - npm install

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run lint

cache:
  directories:
    - "node_modules"

branches:
  only: master

notifications:
  email:
    on_success: never
    on_failure: always

